### ISSUE TITLE
Error I cannot explain

### ISSUE THREAD

**Issue by hayk94** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#18]
Hello I am getting this error when trying to run a job. But I can't get any idea why this happens. Do you see anything here?

```
I20171227-14:26:26.755(4)? Exception while invoking method 'trigger_WELCOME_AND_VERIFY' TypeError: Cannot read property 'name' of undefined
I20171227-14:26:26.755(4)?     at Jobs.private.run (packages/msavin_sjobs.js:206:48)
I20171227-14:26:26.755(4)?     at Object.Jobs.run (packages/msavin_sjobs.js:705:26)
I20171227-14:26:26.755(4)?     at DDPCommon.MethodInvocation.runJobTrigger_LIGHTBOX_MUST_HAVE_ELEMENTS (imports/02-Notifications/server/methods.js:18:10)
I20171227-14:26:26.755(4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20171227-14:26:26.755(4)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
I20171227-14:26:26.755(4)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
I20171227-14:26:26.755(4)?     at resolve (packages/ddp-server/livedata_server.js:1684:36)
I20171227-14:26:26.756(4)?     at new Promise (<anonymous>)
I20171227-14:26:26.757(4)?     at Server.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
I20171227-14:26:26.757(4)?     at Server.apply (packages/ddp-server/livedata_server.js:1622:26)
I20171227-14:26:26.757(4)?     at Server.call (packages/ddp-server/livedata_server.js:1604:17)
I20171227-14:26:26.757(4)?     at EventEmitter.GettingStarted.js.Emitter.on (imports/02-Notifications/server/listeners/GettingStarted.js:21:10)
I20171227-14:26:26.757(4)?     at emitNone (events.js:105:13)
I20171227-14:26:26.757(4)?     at EventEmitter.emit (events.js:207:7)
I20171227-14:26:26.757(4)?     at DDPCommon.MethodInvocation.trigger_GETTING_STARTED (imports/02-Notifications/server/methods.js:8:13)
I20171227-14:26:26.757(4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20171227-14:26:26.758(4)?  => awaited here:
I20171227-14:26:26.758(4)?     at Promise.await (/Users/hayksafaryan/.meteor/packages/promise/.0.10.0.3vpk2l.pdr8h++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
I20171227-14:26:26.758(4)?     at Server.apply (packages/ddp-server/livedata_server.js:1635:14)
I20171227-14:26:26.758(4)?     at Server.call (packages/ddp-server/livedata_server.js:1604:17)
I20171227-14:26:26.758(4)?     at EventEmitter.GettingStarted.js.Emitter.on (imports/02-Notifications/server/listeners/GettingStarted.js:21:10)
I20171227-14:26:26.758(4)?     at emitNone (events.js:105:13)
I20171227-14:26:26.759(4)?     at EventEmitter.emit (events.js:207:7)
I20171227-14:26:26.759(4)?     at DDPCommon.MethodInvocation.trigger_GETTING_STARTED (imports/02-Notifications/server/methods.js:8:13)
I20171227-14:26:26.759(4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20171227-14:26:26.759(4)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
I20171227-14:26:26.759(4)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
I20171227-14:26:26.759(4)?     at resolve (packages/ddp-server/livedata_server.js:1684:36)
I20171227-14:26:26.759(4)?     at new Promise (<anonymous>)
I20171227-14:26:26.759(4)?     at Server.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
I20171227-14:26:26.759(4)?     at Server.apply (packages/ddp-server/livedata_server.js:1622:26)
I20171227-14:26:26.759(4)?     at Server.call (packages/ddp-server/livedata_server.js:1604:17)
I20171227-14:26:26.760(4)?     at EventEmitter.WelcomeAndVerify.js.Emitter.on (imports/02-Notifications/server/listeners/WelcomeAndVerify.js:39:10)
I20171227-14:26:26.760(4)?  => awaited here:
I20171227-14:26:26.760(4)?     at Promise.await (/Users/hayksafaryan/.meteor/packages/promise/.0.10.0.3vpk2l.pdr8h++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
I20171227-14:26:26.760(4)?     at Server.apply (packages/ddp-server/livedata_server.js:1635:14)
I20171227-14:26:26.760(4)?     at Server.call (packages/ddp-server/livedata_server.js:1604:17)
I20171227-14:26:26.760(4)?     at EventEmitter.WelcomeAndVerify.js.Emitter.on (imports/02-Notifications/server/listeners/WelcomeAndVerify.js:39:10)
I20171227-14:26:26.760(4)?     at emitNone (events.js:105:13)
I20171227-14:26:26.760(4)?     at EventEmitter.emit (events.js:207:7)
I20171227-14:26:26.761(4)?     at DDPCommon.MethodInvocation.trigger_WELCOME_AND_VERIFY (imports/02-Notifications/server/methods.js:12:13)
I20171227-14:26:26.761(4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20171227-14:26:26.761(4)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20171227-14:26:26.761(4)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
I20171227-14:26:26.761(4)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20171227-14:26:26.761(4)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
I20171227-14:26:26.761(4)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20171227-14:26:26.761(4)?     at new Promise (<anonymous>)
I20171227-14:26:26.761(4)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20171227-14:26:26.761(4)?     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by msavin** [comment]
Can you post the code that you are using to register and run the job?

**Comment by msavin** [comment]
Assuming you resolved the issue. If it persists, please let me know.
