### ISSUE TITLE
Did not check() all arguments during publisher 'jobsDebugger' error when attempting to load Gui debugger

### ISSUE THREAD

**Issue by stevenqzhang** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#24]
Not sure why, but the exception I get is this:

```
Exception from sub jobsDebugger id sTZfK5nZtaHLusoqT Error: Did not check() all arguments during publisher 'jobsDebugger'
I20180131-22:57:12.996(-8)?     at ArgumentChecker.throwUnlessAllArgumentsHaveBeenChecked (packages/check.js:483:13)
I20180131-22:57:12.996(-8)?     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:131:16)
I20180131-22:57:12.996(-8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
I20180131-22:57:12.996(-8)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)
```

**Comment by msavin** [comment]
Ah - `audit-argument-checks` is probably behind it. I'll push up an update soon

**Comment by stevenqzhang** [comment]
I can pull up the GUI debugger in the meantime, but this error throws anytime I try to do anything. Is there a workaround for now?

**Comment by msavin** [comment]
@stevenqzhang v1.0.1 should have you back in business. please let me know if you experience another issue :)

**Comment by stevenqzhang** [comment]
@msavin i upgraded to 

```
msavin:sjobs@3.0.6
msavin:sjobs-ui-blaze@3.0.1
```

Still getting the error
